set_property SRC_FILE_INFO {cfile:C:/devWorks/IMU_SOC/IMU_SOC.srcs/constrs_1/new/IO_Ports.xdc rfile:../../../IMU_SOC.srcs/constrs_1/new/IO_Ports.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y16 [get_ports IIC_0_0_scl_io]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y17 [get_ports IIC_0_0_sda_io]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y18 [get_ports IIC_0_scl_io]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y19 [get_ports IIC_0_sda_io]
